config/routes.rb
Rails.application.routes.draw do

  get '/contact' => 'welcome#contact'
  get '/about' => 'welcome#about'
  root 'welcome#index'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def params_action(action)
    return (params[:controller] == 'welcome' && params[:action] == action) ? 'active' : ''
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>IndoreTexi</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
    <%= render partial: 'shared/header' %>
	  <%= yield %>

	</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <ul class="nav navbar-nav pull-right marginRight100">
    <li class="<%= params_action('index') %>"><a class="navbar-brand navbar-font-color" href="<%= root_url %>">Home</a></li>	
    <li class="<%= params_action('contact')%>"><a class="navbar-brand navbar-font-color" href="<%= contact_url %>">Contact</a></li>
    <li class="<%= params_action('about') %>"><a class="navbar-brand navbar-font-color" href="<%= about_url %>">About</a></li>
  </ul>
</nav>

app/views/welcome/contact.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div class='row'>
	<div class='col-md-8' style='height: 400px;' id="map-canvas">
	</div>
</div>
<div class="row">
  <div class="col-md-1"> Address:</div><div class="col-md-4"></div>
  <div class="col-md-6"></div>
</div>

<script type="text/javascript">
function initialize() {
  var mapOptions = {
    zoom: 17,
    center: new google.maps.LatLng(22.752458, 75.89076)
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  var marker = new google.maps.Marker({
    position: map.getCenter(),
    map: map,
    title: 'Click to zoom'
  });

  google.maps.event.addListener(map, 'center_changed', function() {
    // 3 seconds after the center of the map has changed, pan back to the
    // marker.
    window.setTimeout(function() {
      map.panTo(marker.getPosition());
    }, 300);
  });

  google.maps.event.addListener(marker, 'click', function() {
    map.setZoom(8);
    map.setCenter(marker.getPosition());
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

</script>